; ESP12F Hub — receives ESP32 reports and forwards to laptop over serial.

[env:esp12e]
platform      = espressif8266
board         = esp12e
framework     = arduino
monitor_speed = 115200
build_flags =
  -DTARGET_MAC
  -DTARGET_MAC_0=0xE6
  -DTARGET_MAC_1=0xA6
  -DTARGET_MAC_2=0x73
  -DTARGET_MAC_3=0x84
  -DTARGET_MAC_4=0x7F
  -DTARGET_MAC_5=0xE3
